apiVersion: v1
kind: Service
metadata:
  name: springboot-k8ssvc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 3080       # Clients will use this port
      targetPort: 8080 # Forward traffic to the container's port
  type: LoadBalancer
