replicaCount: 2

image:
  repository: "140023400586.dkr.ecr.ap-south-1.amazonaws.com/dec-2025"
  tag: "V2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: springboot.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

